### ISSUE TITLE
投票の終了タグが表示されない？ helperがおかしい

### ISSUE THREAD

**Issue by Rp7rf** [chaptmn/vote_system#100]
一番下のが終了状態のはず...
<img width="814" alt="2017-07-14 1 23 48" src="https://user-images.githubusercontent.com/8898432/28176643-2c9d968e-6833-11e7-9a60-a132009c2239.png">

**Comment by chaptmn** [comment]
これってもうfixしてあるよね？

**Comment by Rp7rf** [comment]
時間の方がバグってた問題
#102
