### ISSUE TITLE
Googleアカウントで入っていない人の扱い

### ISSUE THREAD

**Issue by Rp7rf** [chaptmn/vote_system#62]
投票できないだけ？
全てhidden？

**Comment by chaptmn** [comment]
ログインしてない人ってことだよね？まだはじいたりする処理は考えてない！ログインしてないと投票できないようにした方がいいよね。

**Comment by Rp7rf** [comment]
そうそう！！その処理せねば...(投票以外の機能つけるか全てhiddenにするか

**Comment by chaptmn** [comment]
あー、投票しようとしたらログイン画面（google認証）に飛ばすのはどう？

**Comment by Rp7rf** [comment]
:+1:
