### ISSUE TITLE
これ解決したい

### ISSUE THREAD

**Issue by chaptmn** [chaptmn/vote_system#67]
リンク化したい
<img width="945" alt="2017-06-28 0 49 32" src="https://user-images.githubusercontent.com/17764655/27596934-ea29a2d2-5b9b-11e7-98bc-26156c16e5cf.png">

**Comment by Rp7rf** [comment]
http://yohshiy.blog.fc2.com/blog-category-24.html
bar chartにはつけられないみたい？
table chartにはつけられるみたい！
