### ISSUE TITLE
投票できないようになっている...(どこだろ...

### ISSUE THREAD

**Issue by Rp7rf** [chaptmn/vote_system#82]

**Comment by chaptmn** [comment]
なんでエラーだろ？

**Comment by chaptmn** [comment]
なんで→なんて

**Comment by Rp7rf** [comment]
パッと見て覚えてない...JSっぽい

**Comment by chaptmn** [comment]
頼んま

**Comment by Rp7rf** [comment]
http://qiita.com/hc_isobe/items/a29860d3e86a6bc5fd3e js.erbというのがあるらしいけどもっとスマートにjsにrubyのコード渡したい...

**Comment by Rp7rf** [comment]
<script src="https://cdnjs.cloudflare.com/ajax/libs/gsap/latest/TweenMax.min.js" />
ここのせいっぽい(動かないの

**Comment by chaptmn** [comment]
mjk やってもらえる？
