### ISSUE TITLE
無限に投票できてしまう問題。

### ISSUE THREAD

**Issue by chaptmn** [chaptmn/vote_system#88]
# What
投票に際して、画面には3票までと書いてあるが、投票後再び戻ってきてもさらに3票投票できる。
# Why
validateできてない

**Comment by Rp7rf** [comment]
User.firstが選ばれてるからみたい...(@chaptmn　わかりそう?

**Comment by Rp7rf** [comment]
https://github.com/chaptmn/vote_system/pull/92
